apiVersion: apps/v1
kind: Deployment
metadata:  
  name: springboot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: springboot
      labels:
        app: spring
    spec:
      containers:
      - name: springboot-container
        image: amulyaproject/my-spring-pro
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "300Mi"
        env:
        - name: MONGO_DB_HOSTNAME
          value: Mongodbsv
        - name: MONGO_DB_USERNAME
          value: dbusername
        - name: MONGO_DB_PASSWORD
          value: dbpsswd
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
